# Generated by Django 5.1.3 on 2024-11-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_waitlistentry_updated_at_alter_waitlistentry_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
