# Generated by Django 5.1.4 on 2024-12-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="store_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
