# Generated by Django 5.1.6 on 2025-02-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_editor_link'),
        ('api', '0008_map'),
    ]

    operations = [
    ]
