# Generated by Django 5.1.4 on 2025-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_camera"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="is_active",
        ),
        migrations.AddField(
            model_name="camera",
            name="camera_type",
            field=models.CharField(default="shoplift", max_length=50),
        ),
        migrations.AlterField(
            model_name="camera",
            name="camera_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="camera",
            name="video_path",
            field=models.CharField(max_length=255),
        ),
    ]
