# Generated by Django 5.1.4 on 2025-04-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_remove_camera_is_active_camera_camera_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="camera",
            name="camera_type",
            field=models.CharField(
                choices=[
                    ("shoplift", "Shoplifting Detection"),
                    ("age_gender", "Age & Gender Detection"),
                ],
                default="shoplift",
                max_length=50,
            ),
        ),
    ]
