# Generated by Django 5.1.4 on 2025-04-26 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_camera_is_active_alter_camera_camera_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="camera_type",
            field=models.CharField(
                choices=[
                    ("shoplift", "Shoplifting Detection"),
                    ("age_gender", "Age & Gender Detection"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="camera",
            unique_together={("user", "camera_id", "camera_type")},
        ),
    ]
