# Generated by Django 5.1.4 on 2025-04-26 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_camera_camera_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="camera",
            index=models.Index(
                fields=["user", "camera_type", "is_active"],
                name="api_camera_user_id_479e48_idx",
            ),
        ),
    ]
