# Generated by Django 5.1.4 on 2025-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_camera_api_camera_user_id_479e48_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeopleCounterCamera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera_id", models.CharField(max_length=100, unique=True)),
                ("video_path", models.CharField(max_length=255)),
                ("entry_count", models.IntegerField(default=0)),
                ("entry_points", models.JSONField(default=list)),
                ("exit_points", models.JSONField(default=list)),
                ("is_running", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
