# Generated by Django 5.1.4 on 2025-04-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_peoplecountercamera"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="entry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="camera",
            name="entry_points",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="camera",
            name="exit_points",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="camera",
            name="is_running",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="camera",
            name="camera_type",
            field=models.CharField(
                choices=[
                    ("shoplift", "Shoplifting Detection"),
                    ("age_gender", "Age & Gender Detection"),
                    ("people_counter", "People Counter"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
