# Generated by Django 5.1.4 on 2025-04-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_camera_entry_count_camera_entry_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
