# Generated by Django 5.1.4 on 2025-04-30 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_camera_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("total_events", models.IntegerField(default=0)),
                ("suspicious_events", models.IntegerField(default=0)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_data",
                        to="api.camera",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["camera", "timestamp"],
                        name="api_detecti_camera__b64b27_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="api_detecti_timesta_8809e8_idx"
                    ),
                ],
            },
        ),
    ]
