# Generated by Django 5.1.4 on 2025-05-08 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_detectiondata"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGenderDetectionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("male_count", models.IntegerField(default=0)),
                ("female_count", models.IntegerField(default=0)),
                ("age_0_3_count", models.IntegerField(default=0)),
                ("age_4_7_count", models.IntegerField(default=0)),
                ("age_8_12_count", models.IntegerField(default=0)),
                ("age_13_20_count", models.IntegerField(default=0)),
                ("age_21_32_count", models.IntegerField(default=0)),
                ("age_33_43_count", models.IntegerField(default=0)),
                ("age_44_53_count", models.IntegerField(default=0)),
                ("age_60_100_count", models.IntegerField(default=0)),
                ("total_detections", models.IntegerField(default=0)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_gender_data",
                        to="api.camera",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PeopleCounterCamera",
        ),
        migrations.AddIndex(
            model_name="agegenderdetectiondata",
            index=models.Index(
                fields=["camera", "timestamp"], name="api_agegend_camera__8f3157_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agegenderdetectiondata",
            index=models.Index(
                fields=["timestamp"], name="api_agegend_timesta_7e0191_idx"
            ),
        ),
    ]
