# Generated by Django 5.1.4 on 2025-05-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_agegenderdetectiondata_delete_peoplecountercamera_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeopleCounterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("entry_count", models.IntegerField(default=0)),
                (
                    "zone_name",
                    models.CharField(blank=True, default="Main Zone", max_length=100),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people_counter_data",
                        to="api.camera",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["camera", "timestamp"],
                        name="api_peoplec_camera__0f5ceb_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="api_peoplec_timesta_754d86_idx"
                    ),
                    models.Index(
                        fields=["zone_name"], name="api_peoplec_zone_na_ff6c2e_idx"
                    ),
                ],
            },
        ),
    ]
