# Generated by Django 5.1.4 on 2025-05-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_peoplecounterdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopliftingAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "video_clip",
                    models.FileField(
                        blank=True, null=True, upload_to="shoplifting_alerts/"
                    ),
                ),
                (
                    "video_thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="shoplifting_thumbnails/"
                    ),
                ),
                ("is_reviewed", models.BooleanField(default=False)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("auto_delete_date", models.DateTimeField(blank=True, null=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api.camera",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["camera", "timestamp"],
                        name="api_shoplif_camera__7af952_idx",
                    ),
                    models.Index(
                        fields=["is_reviewed"], name="api_shoplif_is_revi_3fe7e2_idx"
                    ),
                    models.Index(
                        fields=["auto_delete_date"],
                        name="api_shoplif_auto_de_7b70fd_idx",
                    ),
                ],
            },
        ),
    ]
