# Generated by Django 5.1.4 on 2025-05-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_shopliftingalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopliftingalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("recording_in_progress", "Recording in Progress"),
                    ("completed", "Completed"),
                    ("reviewed", "Reviewed"),
                ],
                default="new",
                max_length=25,
            ),
        ),
    ]
