# Generated by Django 5.1.4 on 2025-05-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_shopliftingalert_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopliftingalert",
            name="annotated_video_clip",
            field=models.FileField(
                blank=True, null=True, upload_to="shoplifting_alerts_annotated/"
            ),
        ),
        migrations.AddField(
            model_name="shopliftingalert",
            name="detection_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shopliftingalert",
            name="has_annotated_version",
            field=models.BooleanField(default=False),
        ),
    ]
