# Generated by Django 5.1.4 on 2025-05-09 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_shopliftingalert_annotated_video_clip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopliftingalert",
            name="annotated_video_clip",
        ),
        migrations.RemoveField(
            model_name="shopliftingalert",
            name="has_annotated_version",
        ),
    ]
