# Generated by Django 5.1.4 on 2025-05-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_remove_shopliftingalert_annotated_video_clip_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="shopliftingalert",
            name="api_shoplif_auto_de_7b70fd_idx",
        ),
        migrations.AlterField(
            model_name="shopliftingalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("reviewed", "Reviewed"),
                ],
                default="processing",
                max_length=25,
            ),
        ),
        migrations.AddIndex(
            model_name="shopliftingalert",
            index=models.Index(fields=["status"], name="api_shoplif_status_2f0123_idx"),
        ),
    ]
