# Generated by Django 5.1.4 on 2025-05-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_remove_shopliftingalert_api_shoplif_auto_de_7b70fd_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopliftingalert",
            name="video_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="shopliftingalert",
            index=models.Index(
                fields=["video_ready"], name="api_shoplif_video_r_17c5fb_idx"
            ),
        ),
    ]
